FROM node:18

WORKDIR /app

# Copie o package.json e package-lock.json (se existir) para instalar dependências
COPY package.json package-lock.json* ./

# Instale todas as dependências listadas no package.json
RUN npm install --legacy-peer-deps

# Copie o restante dos arquivos do frontend
COPY . .

# Exponha a porta 3000
EXPOSE 3000

# Inicie o aplicativo
CMD ["npm", "start"]