FROM node:18

WORKDIR /app

# Copie apenas package.json e package-lock.json para instalar dependências
COPY package.json package-lock.json* ./

# Instale as dependências usando npm ci
RUN npm ci --legacy-peer-deps

# Exponha a porta 3000
EXPOSE 3000

# Inicie o aplicativo
CMD ["npm", "start"]