services:
  recomendador:
    build:
      context: .
      dockerfile: Dockerfile
    image: recomendador-g1:latest
    container_name: recomendador-g1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]