version: '3.8'

services:
  recomendador:
    build:
      context: .
      dockerfile: Dockerfile
    image: recomendador-g1:latest
    container_name: recomendador-g1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data/files/treino:/app/data/files/treino
      - ./data/itens/itens:/app/data/itens/itens
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn recomendador:app --host 0.0.0.0 --port 8000
